### ISSUE TITLE
 Received malformed response from transform AWS::Serverless-2016-10-31

### ISSUE THREAD

**Issue by orr-levinger** [aws/aws-lambda-dotnet#765]
## Description
template wasnt changed at all just redeployed and got this error.
there is no information in the logs so cant really understand whats wrong..

## Reproduction Steps
same as https://github.com/aws/aws-lambda-dotnet/issues/761

Serverless: Typescript compiled.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: [serverless-plugin-split-stacks]: Summary: 17 resources migrated in to 2 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:
Serverless: [serverless-plugin-split-stacks]:    - (root): 195
Serverless: [serverless-plugin-split-stacks]:    - APINestedStack: 10
Serverless: [serverless-plugin-split-stacks]:    - PermissionsNestedStack: 7
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service sls-blind-chat.zip file to S3 (23.86 MB)...
Serverless: Uploading custom CloudFormation resources...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - sls-blind-chat-dev-stack
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - sls-blind-chat-dev-stack
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - sls-blind-chat-dev-stack
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - sls-blind-chat-dev-stack
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - sls-blind-chat-dev-stack
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A956109742295%3Astack%2Fsls-blind-chat-dev-stack%2Fcac3ba10-29e0-11eb-b791-0a73682547f5
 
  Serverless Error ---------------------------------------
 
  An error occurred: sls-blind-chat-dev-stack - Received malformed response from transform AWS::Serverless-2016-10-31.

This is a :bug: bug-report

**Comment by MatiasSasRise** [comment]
Same issue here: us-east-1

**Comment by agustinezequielgomez-rise** [comment]
I'm having the same issue on us-east-1

**Comment by agworkscode** [comment]
Same issue here. us-east-1

**Comment by ashishdhingra** [comment]
Hi,

Good morning.

Looks like there is a service outage for **us-east-1** region. Service teams are working on it and the issue should be resolved soon.

Thanks,
Ashish

**Comment by KitFristo** [comment]
I am also seeing the same issue in us-east-1.

**Comment by MattCopenhaver** [comment]
Same issue here.

**Comment by sab3d** [comment]
+1

**Comment by rahulict** [comment]
Same issue here.

**Comment by CJX3M** [comment]
Same issue here, deploying some lambdas

**Comment by mochi-co** [comment]
Same issue here also, deploying Go lambdas

**Comment by ItayGoren** [comment]
same issue - python lambdas

**Comment by jewelsjacobs** [comment]
➕ 1

**Comment by RONITKHUNGAR** [comment]
Same issues , for almost 2 hours

**Comment by slitsevych** [comment]
apparently us-east-1 region is not having a good time right now. 

- CloudWatchEvents operational issue
- Cognito operational issue
- Cloudwatch operational issue
- Kinesis operational issue:

> [08:12 AM PST] Kinesis Data Streams customers are still experiencing increased API errors. This is also impacting other services, including ACM, Amplify Console, API Gateway, AppStream2, AppSync, Athena, Cloudformation, Cloudtrail, CloudWatch, Cognito, Connect, DynamoDB, EventBridge, IoT Services, Lambda, LEX, Managed Blockchain, Resource Groups, SageMaker, Support Console, and Workspaces. We are continuing to work on identifying root cause.

**Comment by KitFristo** [comment]
As @slitsevych pointed out, that region is having a lot of outages. You can find them [here](https://status.aws.amazon.com/), although the outages are also affecting the dashboard it seems.

**Comment by AdamT213** [comment]
same here, ruby and node.js lambdas

**Comment by pam81** [comment]
+1

**Comment by ashishdhingra** [comment]
Hi All,

There is a comment in the related old issue https://github.com/aws/aws-lambda-dotnet/issues/761 that the problem is fixed. Please verify the same and confirm if we could close this issue.

Thanks,
Ashish

**Comment by KitFristo** [comment]
@ashishdhingra I'm still seeing the issue as of 11:18 PM EST.

**Comment by manisha1895** [comment]
Worked for me now, able to deploy sam stack in us-east-1 region

**Comment by ashishdhingra** [comment]
As per service dashboard at https://status.aws.amazon.com/, everything appears to be running normally.
